export const API_POLYGONSCAN_URL = 'https://api.polygonscan.com/api?';

export const ETHERSCAN_API_SECRET_KEY = 'G1UDIXWQ3YZRNQJ6CVVNYZQF1AAHD1JGTK';
export const POLYGONSCAN_API_SECRET_KEY = '55NTQJTESXPJMPCHNFQYR53CPJBBNPMFM3';
export const BSCSCAN_API_SECRET_KEY = '7PD23CVR63SYYWDMXWW3K52JP13HQMMXSB';
//export const BSCSCAN_API_SECRET_KEY = 'D5YZCWPQ2J1QKUEUKVJDTF3VMAPK8PE5WE';
export const EXPLORER_API_SECRET_KEY: Record<string, string> = {
  '1': ETHERSCAN_API_SECRET_KEY,
  '3': ETHERSCAN_API_SECRET_KEY,
  '4': ETHERSCAN_API_SECRET_KEY,
  '5': ETHERSCAN_API_SECRET_KEY,
  '42': ETHERSCAN_API_SECRET_KEY,
  '56': BSCSCAN_API_SECRET_KEY,
  '97': BSCSCAN_API_SECRET_KEY,
  '137': POLYGONSCAN_API_SECRET_KEY
};
